services:
  nginx-http-flv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-rtmp
    #network_mode: host
    ports:
      - "1935:1935"
      - "8080:8080"
    tmpfs:
      - /tmp/hls:exec,rw,noatime,mode=1777,size=128m
    volumes:
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
